# Generated by Django 4.2 on 2023-04-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=16, verbose_name="이름"),
        ),
    ]
